{
 "title": "Monitoring-iLO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "label": "Site", "query": { "query": "label_values(site)" } },
   {
    "name": "ilo_ip",
    "label": "ilo_ip",
    "query": {
     "query": "label_values({site=\"$site\"},ilo_ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ilo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Etat du serveur",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_server_status{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Consommation serveur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ilo_power_consumption_watts{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alimentation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_power_redundancy_status{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Etat general",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_summary_component_health{component!=\"PowerSupplies\", ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Température chipset",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{sensor=\"chipset\", ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Température  ambiante ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{sensor=\"inlet\", ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature cpu",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{sensor=\"cpu\", ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Température chipset",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_temperature_celsius{sensor=\"bmc\", ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vitesse des ventilateurs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_fan_info{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SYSTEM INFO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ilo_server_info{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ilo_memory_total_gb{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "ilo_device_info{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ilo_cpu_info{ilo_ip=\"$ilo_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ilo_storage_logical_disk{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "ilo_storage_physical_disk{ilo_ip=\"$ilo_ip\", site=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}